import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import ts from 'typescript';
const options={compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}};
const toURL=source=>`data:text/javascript;base64,${Buffer.from(ts.transpileModule(source,options).outputText).toString('base64')}`;
const demoSource=await readFile(new URL('../src/demo.ts',import.meta.url),'utf8');
const demoURL=toURL(demoSource);
const apiSource=await readFile(new URL('../src/api.ts',import.meta.url),'utf8');
const api=await import(toURL(apiSource.replace('"./demo"',JSON.stringify(demoURL))));
const demo=await import(demoURL);
const storage=()=>{const data=new Map();return {getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)};};
test('standalone demo completes a send/receive journey without network or real profile writes',async()=>{
  let requests=0;
  globalThis.window={location:{pathname:'/tkl/',search:'?mode=demo',origin:'http://localhost'},sessionStorage:storage(),localStorage:storage(),setTimeout,clearTimeout};
  window.localStorage.setItem('trainmeet-tkl.browser-config','real-profile-untouched');
  globalThis.fetch=()=>{requests++;throw new Error('Demo must never fetch');};
  await api.resetTerminalConfig();
  assert.equal((await api.loadAuthStatus()).authenticated,true);
  const runtime=(await api.loadRuntime());
  assert.equal(runtime.source,'demo');
  assert.equal(runtime.snapshot.meet.id,'demo-only');
  assert.equal((await api.loadTerminalConfig()).configured,false);
  const config={terminal_name:'Demo',server_url:'http://real-server.invalid',station_id:'demo-a',orientation:'portrait'};
  await api.saveTerminalConfig(config);
  let context=await api.loadTklContext('demo-a');
  const scope={meet_generation:context.meet_generation,station_id:'demo-a'};
  await api.startTklShift({...scope,operator_name:'Tester',terminal_name:'Demo'});
  await api.updateTklMovement({...scope,movement_id:'demo-101-a',arrival:'none',departure:'positioned',actual_track:'2',event_type:'departure_positioned'});
  assert.equal((await api.loadTklContext('demo-a')).movements['demo-101-a'].actualTrack,'2');
  const line={...scope,connection_id:'demo-line',train_number:'101'};
  assert.equal((await api.performTklLineAction({...line,action:'request'})).state,'reserved');
  assert.equal((await api.performTklLineAction({...line,action:'cancel'})).state,'free');
  await api.performTklLineAction({...line,action:'request'});
  await api.performTklLineAction({...line,action:'depart'});
  await assert.rejects(api.performTklLineAction({...line,action:'cancel'}));
  await api.saveTerminalConfig({...config,station_id:'demo-b'});
  await api.startTklShift({meet_generation:1,station_id:'demo-b',operator_name:'Tester',terminal_name:'Demo'});
  assert.equal((await api.performTklLineAction({...line,station_id:'demo-b',action:'arrive'})).state,'free');
  assert.equal((await api.loadRuntime()).snapshot.train_positions[0].station_id,'demo-b');
  context=await api.loadTklContext('demo-b');
  await api.finishTklShift({meet_generation:1,station_id:'demo-b',shift_id:context.shift.shift_id,status:'closed'});
  assert.equal((await api.loadTklContext('demo-b')).shift,null);
  await assert.rejects(api.updateTklMovement({...scope,station_id:'real-station',movement_id:'real-train'}));
  await assert.rejects(api.loginAdmin('admin','never-sent'));
  await assert.rejects(api.startTerminalUpdate());
  assert.equal(requests,0);
  assert.equal(window.localStorage.getItem('trainmeet-tkl.browser-config'),'real-profile-untouched');
  // A fresh module (page reload) restores only this tab's demo state.
  const reloaded=await import(toURL(demoSource+'\n// isolated reload'));
  assert.equal(reloaded.loadDemoConfig().station_id,'demo-b');
  await api.resetTerminalConfig();
  assert.equal(demo.demoSnapshot().connection_states[0].state,'free');
  assert.equal(demo.loadDemoConfig().configured,false);
  assert.equal(window.localStorage.getItem('trainmeet-tkl.browser-config'),'real-profile-untouched');
});
